# Generated by Django 6.0.1 on 2026-01-27 09:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField()),
                ('user_id', models.UUIDField()),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('waitlisted', 'Waitlisted')], default='confirmed', max_length=20)),
                ('attendee_name', models.CharField(max_length=255)),
                ('attendee_email', models.EmailField(max_length=254)),
                ('attendee_phone', models.CharField(blank=True, max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'registrations',
                'indexes': [models.Index(fields=['event_id'], name='registratio_event_i_e5bf77_idx'), models.Index(fields=['user_id'], name='registratio_user_id_6e12f5_idx'), models.Index(fields=['status'], name='registratio_status_b1ca26_idx')],
                'unique_together': {('event_id', 'user_id')},
            },
        ),
    ]
