# Generated by Django 6.0.1 on 2026-01-27 10:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField()),
                ('user_id', models.UUIDField()),
                ('position', models.IntegerField()),
                ('priority', models.IntegerField(default=0)),
                ('is_promoted', models.BooleanField(default=False)),
                ('promoted_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'waitlists',
                'ordering': ['position'],
                'indexes': [models.Index(fields=['event_id', 'position'], name='waitlists_event_i_92824d_idx'), models.Index(fields=['event_id', 'is_promoted'], name='waitlists_event_i_45d5b2_idx')],
                'unique_together': {('event_id', 'user_id')},
            },
        ),
    ]
