# Generated by Django 6.0.1 on 2026-01-27 10:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_waitlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacityRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(unique=True)),
                ('max_capacity', models.IntegerField()),
                ('warning_threshold', models.IntegerField()),
                ('allow_reservations', models.BooleanField(default=True)),
                ('reservation_timeout_minutes', models.IntegerField(default=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'capacity_rules',
                'indexes': [models.Index(fields=['event_id'], name='capacity_ru_event_i_55b2c4_idx')],
            },
        ),
    ]
