# Generated by Django 6.0.1 on 2026-01-27 11:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0004_registrationform_customfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField()),
                ('group_name', models.CharField(max_length=255)),
                ('group_leader_id', models.UUIDField()),
                ('group_leader_email', models.EmailField(max_length=254)),
                ('min_size', models.IntegerField(default=2)),
                ('max_size', models.IntegerField()),
                ('current_size', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('price_per_person', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'group_registrations',
                'indexes': [models.Index(fields=['event_id'], name='group_regis_event_i_924df0_idx'), models.Index(fields=['group_leader_id'], name='group_regis_group_l_9cf8f4_idx')],
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='domain.groupregistration')),
            ],
            options={
                'db_table': 'group_members',
                'indexes': [models.Index(fields=['group', 'user_id'], name='group_membe_group_i_a6045a_idx')],
                'unique_together': {('group', 'user_id')},
            },
        ),
    ]
