# Generated by Django 6.0.1 on 2026-01-27 11:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0005_groupregistration_groupmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(unique=True)),
                ('total_registrations', models.IntegerField(default=0)),
                ('confirmed_registrations', models.IntegerField(default=0)),
                ('cancelled_registrations', models.IntegerField(default=0)),
                ('total_waitlist', models.IntegerField(default=0)),
                ('promoted_from_waitlist', models.IntegerField(default=0)),
                ('total_groups', models.IntegerField(default=0)),
                ('total_group_members', models.IntegerField(default=0)),
                ('capacity_utilization', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'registration_analytics',
                'indexes': [models.Index(fields=['event_id'], name='registratio_event_i_8e34f6_idx')],
            },
        ),
    ]
