# Generated by Django 6.0.1 on 2026-01-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0004_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('REGISTRATION', 'Registration'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('EMAIL_VERIFICATION', 'Email Verification'), ('PASSWORD_RESET', 'Password Reset'), ('PASSWORD_CHANGE', 'Password Change')], max_length=50)),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='audit_logs_event_t_1d94d4_idx'), models.Index(fields=['user_id', 'created_at'], name='audit_logs_user_id_fbfd51_idx')],
            },
        ),
    ]
