# Generated by Django 6.0.1 on 2026-01-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domain", "0012_userrole"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountDeactivation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_id", models.CharField(db_index=True, max_length=255, unique=True)),
                ("deactivated_at", models.DateTimeField(auto_now_add=True)),
                ("grace_period_ends", models.DateTimeField()),
                ("is_anonymized", models.BooleanField(default=False)),
                ("anonymized_at", models.DateTimeField(blank=True, null=True)),
                ("reason", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "account_deactivations",
                "ordering": ["-deactivated_at"],
            },
        ),
    ]
