# Generated by Django 6.0.1 on 2026-01-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domain", "0013_accountdeactivation"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountdeactivation",
            name="is_permanently_deactivated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="accountdeactivation",
            name="permanently_deactivated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
