# Generated by Django 6.0.1 on 2026-01-27 08:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=10000)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('unlisted', 'Unlisted')], default='public', max_length=20)),
                ('organizer_id', models.UUIDField()),
                ('organization_id', models.UUIDField(blank=True, null=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('is_all_day', models.BooleanField(default=False)),
                ('venue_id', models.UUIDField(blank=True, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('online_url', models.URLField(blank=True, max_length=500, null=True)),
                ('max_attendees', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'events',
                'indexes': [models.Index(fields=['organizer_id'], name='events_organiz_1c7a2e_idx'), models.Index(fields=['organization_id'], name='events_organiz_2ab269_idx'), models.Index(fields=['status'], name='events_status_8890b6_idx'), models.Index(fields=['start_datetime'], name='events_start_d_2ddaa0_idx'), models.Index(fields=['deleted_at'], name='events_deleted_d23a84_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(blank=True, null=True)),
                ('organizer_id', models.UUIDField()),
                ('draft_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'event_drafts',
                'indexes': [models.Index(fields=['organizer_id'], name='event_draft_organiz_0f35df_idx'), models.Index(fields=['event_id'], name='event_draft_event_i_745bdf_idx'), models.Index(fields=['updated_at'], name='event_draft_updated_248878_idx')],
            },
        ),
    ]
