# Generated by Django 6.0.1 on 2026-01-27 14:04

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSearchIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('tags', models.JSONField(default=list)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('search_rank', models.FloatField(default=0.0)),
                ('view_count', models.IntegerField(default=0)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('event_date', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'event_search_index',
                'indexes': [models.Index(fields=['event_id'], name='event_searc_event_i_d0fcf3_idx'), models.Index(fields=['status', 'is_published'], name='event_searc_status_2520a4_idx'), models.Index(fields=['category'], name='event_searc_categor_88e3fb_idx'), models.Index(fields=['city'], name='event_searc_city_7c9a30_idx'), models.Index(fields=['-search_rank'], name='event_searc_search__50135b_idx'), django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='event_searc_search__403bf2_gin')],
            },
        ),
    ]
