# Generated by Django 6.0.1 on 2026-01-27 17:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0003_tag_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(unique=True)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'event_locations',
                'indexes': [models.Index(fields=['event_id'], name='event_locat_event_i_992e86_idx'), models.Index(fields=['city'], name='event_locat_city_9788be_idx'), models.Index(fields=['country'], name='event_locat_country_961db9_idx'), models.Index(fields=['latitude', 'longitude'], name='event_locat_latitud_9fd94c_idx')],
            },
        ),
        migrations.CreateModel(
            name='LocationSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius_km', models.FloatField(default=10.0)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'location_searches',
                'indexes': [models.Index(fields=['city'], name='location_se_city_9bb9d9_idx'), models.Index(fields=['country'], name='location_se_country_47d370_idx'), models.Index(fields=['latitude', 'longitude'], name='location_se_latitud_cff584_idx')],
            },
        ),
    ]
