# Generated by Django 6.0.1 on 2026-01-27 17:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0004_eventlocation_locationsearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('event_id', models.UUIDField()),
                ('category_score', models.FloatField(default=0.0)),
                ('tag_score', models.FloatField(default=0.0)),
                ('location_score', models.FloatField(default=0.0)),
                ('popularity_score', models.FloatField(default=0.0)),
                ('total_score', models.FloatField(default=0.0)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'recommendation_scores',
                'indexes': [models.Index(fields=['user_id', '-total_score'], name='recommendat_user_id_541f2d_idx'), models.Index(fields=['event_id'], name='recommendat_event_i_3820cc_idx')],
                'unique_together': {('user_id', 'event_id')},
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(unique=True)),
                ('preferred_categories', models.JSONField(default=list)),
                ('preferred_tags', models.JSONField(default=list)),
                ('preferred_cities', models.JSONField(default=list)),
                ('max_distance_km', models.FloatField(default=50.0)),
                ('viewed_events', models.JSONField(default=list)),
                ('registered_events', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_preferences',
                'indexes': [models.Index(fields=['user_id'], name='user_prefer_user_id_63441d_idx')],
            },
        ),
    ]
