# Generated by Django 6.0.1 on 2026-01-27 17:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0005_recommendationscore_userpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_searches', models.IntegerField(default=0)),
                ('unique_queries', models.IntegerField(default=0)),
                ('avg_response_time_ms', models.FloatField(default=0.0)),
                ('popular_queries', models.JSONField(default=list)),
                ('zero_result_queries', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'search_analytics',
                'indexes': [models.Index(fields=['-date'], name='search_anal_date_0dc2c9_idx')],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query_text', models.CharField(max_length=255)),
                ('filters', models.JSONField(default=dict)),
                ('result_count', models.IntegerField(default=0)),
                ('response_time_ms', models.IntegerField(default=0)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'search_queries',
                'indexes': [models.Index(fields=['query_text'], name='search_quer_query_t_f8c040_idx'), models.Index(fields=['-created_at'], name='search_quer_created_824a49_idx'), models.Index(fields=['user_id'], name='search_quer_user_id_64dda1_idx')],
            },
        ),
    ]
