# Generated by Django 6.0.1 on 2026-01-28 02:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0007_mediagallery_mediaitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('document_type', models.CharField(choices=[('agenda', 'Agenda'), ('schedule', 'Schedule'), ('guidelines', 'Guidelines'), ('terms', 'Terms & Conditions'), ('waiver', 'Waiver'), ('other', 'Other')], max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('s3_key', models.CharField(max_length=500)),
                ('access_level', models.CharField(choices=[('public', 'Public'), ('registered', 'Registered Only'), ('organizer', 'Organizer Only')], default='public', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=1)),
                ('previous_version_id', models.UUIDField(blank=True, null=True)),
                ('is_encrypted', models.BooleanField(default=False)),
                ('is_scanned', models.BooleanField(default=False)),
                ('download_count', models.IntegerField(default=0)),
                ('created_by', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'documents',
                'indexes': [models.Index(fields=['event_id', 'document_type'], name='documents_event_i_da0986_idx'), models.Index(fields=['access_level'], name='documents_access__ab8fbf_idx')],
            },
        ),
    ]
