# Generated by Django 6.0.1 on 2026-01-28 07:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0008_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(db_index=True)),
                ('user_id', models.UUIDField(db_index=True)),
                ('provider', models.CharField(choices=[('google', 'Google Calendar'), ('outlook', 'Outlook Calendar'), ('apple', 'Apple Calendar'), ('ical', 'iCal')], max_length=20)),
                ('external_calendar_id', models.CharField(blank=True, max_length=255)),
                ('external_event_id', models.CharField(blank=True, max_length=255)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('sync_token', models.CharField(blank=True, max_length=500)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_error', models.TextField(blank=True)),
                ('event_title', models.CharField(max_length=255)),
                ('event_start', models.DateTimeField()),
                ('event_end', models.DateTimeField()),
                ('event_timezone', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'calendar_events',
                'indexes': [models.Index(fields=['event_id', 'user_id'], name='calendar_ev_event_i_fe6281_idx'), models.Index(fields=['provider', 'sync_status'], name='calendar_ev_provide_600845_idx'), models.Index(fields=['external_event_id'], name='calendar_ev_externa_bef6c5_idx')],
                'unique_together': {('event_id', 'user_id', 'provider')},
            },
        ),
    ]
