# Generated by Django 6.0.1 on 2026-01-28 08:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0009_calendarevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=2000)),
                ('category', models.CharField(choices=[('conference', 'Conference'), ('workshop', 'Workshop'), ('meetup', 'Meetup'), ('webinar', 'Webinar'), ('social', 'Social Event'), ('sports', 'Sports Event'), ('other', 'Other')], max_length=50)),
                ('template_data', models.JSONField(default=dict)),
                ('created_by', models.UUIDField()),
                ('organization_id', models.UUIDField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('organization', 'Organization'), ('public', 'Public')], default='private', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=1)),
                ('parent_template_id', models.UUIDField(blank=True, null=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'event_templates',
                'indexes': [models.Index(fields=['category', 'visibility'], name='event_templ_categor_5c4faa_idx'), models.Index(fields=['created_by'], name='event_templ_created_e38cb1_idx'), models.Index(fields=['organization_id'], name='event_templ_organiz_5af2b0_idx'), models.Index(fields=['is_featured'], name='event_templ_is_feat_ad5f9b_idx')],
            },
        ),
    ]
