# Generated by Django 6.0.1 on 2026-01-28 09:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0010_eventtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventClone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_event_id', models.UUIDField(db_index=True)),
                ('cloned_event_id', models.UUIDField(unique=True)),
                ('cloned_by', models.UUIDField()),
                ('clone_reason', models.CharField(blank=True, max_length=255)),
                ('fields_modified', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'event_clones',
                'indexes': [models.Index(fields=['original_event_id'], name='event_clone_origina_19486f_idx'), models.Index(fields=['cloned_by'], name='event_clone_cloned__50a882_idx')],
            },
        ),
    ]
