# Generated by Django 6.0.1 on 2026-01-29 15:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('quantity', models.IntegerField()),
                ('quantity_sold', models.IntegerField(default=0)),
                ('min_purchase', models.IntegerField(default=1)),
                ('max_purchase', models.IntegerField(default=10)),
                ('sale_start', models.DateTimeField()),
                ('sale_end', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ticket_types',
                'indexes': [models.Index(fields=['event_id', 'is_active'], name='ticket_type_event_i_c71083_idx')],
            },
        ),
    ]
