# Generated by Django 6.0.1 on 2026-01-29 16:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_type_id', models.UUIDField(db_index=True)),
                ('order_id', models.UUIDField(db_index=True)),
                ('attendee_name', models.CharField(max_length=200)),
                ('attendee_email', models.EmailField(max_length=254)),
                ('qr_code_data', models.CharField(max_length=500, unique=True)),
                ('security_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=20)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_in_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tickets',
                'indexes': [models.Index(fields=['ticket_type_id', 'status'], name='tickets_ticket__46ee73_idx'), models.Index(fields=['order_id'], name='tickets_order_i_929c77_idx'), models.Index(fields=['qr_code_data'], name='tickets_qr_code_b1ab07_idx')],
            },
        ),
    ]
