# Generated by Django 6.0.1 on 2026-01-30 08:42

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0004_promocode'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(db_index=True)),
                ('refund_allowed', models.BooleanField(default=True)),
                ('refund_before_hours', models.IntegerField(default=24)),
                ('refund_percentage', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'refund_policies',
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_id', models.UUIDField(db_index=True)),
                ('order_id', models.UUIDField(db_index=True)),
                ('payment_id', models.UUIDField(blank=True, null=True)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejected_reason', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'refunds',
                'indexes': [models.Index(fields=['ticket_id'], name='refunds_ticket__de69e4_idx'), models.Index(fields=['order_id'], name='refunds_order_i_20e1f6_idx'), models.Index(fields=['status'], name='refunds_status_2569d8_idx')],
            },
        ),
    ]
