# Generated by Django 6.0.1 on 2026-01-30 09:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0006_revenue_revenuereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxCalculation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.UUIDField(db_index=True)),
                ('tax_rule_id', models.UUIDField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tax_calculations',
                'indexes': [models.Index(fields=['order_id'], name='tax_calcula_order_i_82db19_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(default='US', max_length=2)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('tax_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20)),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tax_rules',
                'indexes': [models.Index(fields=['country', 'state'], name='tax_rules_country_824f4e_idx')],
            },
        ),
    ]
