# Generated by Django 6.0.1 on 2026-01-30 15:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0008_securityrule_fraudalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_id', models.UUIDField(db_index=True)),
                ('qr_code', models.CharField(max_length=255, unique=True)),
                ('event_id', models.UUIDField(db_index=True)),
                ('attendee_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('expired', 'Expired')], default='active', max_length=20)),
                ('valid_until', models.DateTimeField()),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'offline_tickets',
                'indexes': [models.Index(fields=['ticket_id', 'status'], name='offline_tic_ticket__f76259_idx'), models.Index(fields=['event_id'], name='offline_tic_event_i_f77e4c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ValidationCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(db_index=True)),
                ('cache_data', models.JSONField(default=dict)),
                ('ticket_count', models.IntegerField(default=0)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'validation_cache',
                'indexes': [models.Index(fields=['event_id', 'expires_at'], name='validation__event_i_c5cb59_idx')],
            },
        ),
    ]
