# Generated by Django 6.0.1 on 2026-01-30 16:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0009_offlineticket_validationcache'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkDiscount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(db_index=True)),
                ('min_quantity', models.IntegerField()),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bulk_discounts',
                'indexes': [models.Index(fields=['event_id', 'is_active'], name='bulk_discou_event_i_329d29_idx')],
            },
        ),
        migrations.CreateModel(
            name='GroupBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(db_index=True)),
                ('organizer_id', models.UUIDField(db_index=True)),
                ('group_name', models.CharField(max_length=255)),
                ('min_participants', models.IntegerField()),
                ('max_participants', models.IntegerField()),
                ('current_participants', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'group_bookings',
                'indexes': [models.Index(fields=['event_id', 'status'], name='group_booki_event_i_b28042_idx')],
            },
        ),
    ]
