# Generated by Django 6.0.1 on 2026-01-31 08:25

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0010_bulkdiscount_groupbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(db_index=True)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('total_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('transaction_count', models.IntegerField(default=0)),
                ('previous_period_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sales_metrics',
                'indexes': [models.Index(fields=['event_id', 'period_start'], name='sales_metri_event_i_597cbc_idx')],
            },
        ),
        migrations.CreateModel(
            name='TicketAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(db_index=True)),
                ('total_tickets', models.IntegerField(default=0)),
                ('sold_tickets', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ticket_analytics',
                'indexes': [models.Index(fields=['event_id'], name='ticket_anal_event_i_bf9fa5_idx')],
            },
        ),
    ]
