# Generated by Django 6.0.2 on 2026-02-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('event_data', models.JSONField()),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analytics_events',
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='analytics_e_event_t_c3dcde_idx'), models.Index(fields=['is_processed'], name='analytics_e_is_proc_6db6f4_idx')],
            },
        ),
        migrations.CreateModel(
            name='MetricCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100)),
                ('metric_value', models.FloatField()),
                ('previous_value', models.FloatField(blank=True, null=True)),
                ('calculation_type', models.CharField(max_length=50)),
                ('time_period', models.CharField(blank=True, max_length=50, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'metric_calculations',
                'indexes': [models.Index(fields=['metric_name', 'created_at'], name='metric_calc_metric__8121e9_idx')],
            },
        ),
    ]
