# Generated by Django 6.0.2 on 2026-02-06 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizer_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('layout', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dashboards',
                'indexes': [models.Index(fields=['organizer_id', 'is_active'], name='dashboards_organiz_e528fe_idx')],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('position', models.IntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='domain.dashboard')),
            ],
            options={
                'db_table': 'dashboard_widgets',
                'ordering': ['position'],
                'indexes': [models.Index(fields=['dashboard', 'position'], name='dashboard_w_dashboa_8db101_idx')],
            },
        ),
    ]
