# Generated by Django 6.0.2 on 2026-02-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_dashboard_dashboardwidget'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('check_in_time', models.DateTimeField()),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('is_checked_in', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'attendance_analytics',
                'indexes': [models.Index(fields=['event_id', 'user_id'], name='attendance__event_i_ca8a8c_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=100)),
                ('total_views', models.IntegerField(default=0)),
                ('total_registrations', models.IntegerField(default=0)),
                ('total_attendance', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'event_metrics',
                'indexes': [models.Index(fields=['event_id'], name='event_metri_event_i_a20bf9_idx')],
            },
        ),
    ]
