# Generated by Django 6.0.2 on 2026-02-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0004_financialreport_revenueanalytics'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('total_events_attended', models.IntegerField(default=0)),
                ('total_tickets_purchased', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_analytics',
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('activity_type', models.CharField(max_length=50)),
                ('event_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_activities',
                'indexes': [models.Index(fields=['user_id', 'created_at'], name='user_activi_user_id_c742e0_idx')],
            },
        ),
    ]
