# Generated by Django 6.0.2 on 2026-02-07 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0006_customreport_reporttemplate'),
        ('domain', '0006_visualization_chart'),
    ]

    operations = [
    ]
