# Generated by Django 6.0.2 on 2026-02-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0008_performancemetric_systemhealth'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_name', models.CharField(max_length=200)),
                ('export_format', models.CharField(max_length=50)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('file_path', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'data_exports',
            },
        ),
        migrations.CreateModel(
            name='ExportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=200)),
                ('export_format', models.CharField(max_length=50)),
                ('config', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'export_templates',
            },
        ),
    ]
