# Generated by Django 6.0.2 on 2026-02-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0009_dataexport_exporttemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('findings', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'compliance_reports',
            },
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
                ('resource', models.CharField(default='', max_length=200)),
                ('status', models.CharField(default='success', max_length=50)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_trails',
                'indexes': [models.Index(fields=['user_id', 'created_at'], name='audit_trail_user_id_49e1d4_idx')],
            },
        ),
    ]
