# Generated by Django 6.0.2 on 2026-02-07 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0010_compliancereport_audittrail'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('layout', models.CharField(max_length=50)),
                ('is_optimized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mobile_dashboards',
            },
        ),
        migrations.CreateModel(
            name='MobileWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=20)),
                ('position', models.IntegerField()),
                ('config', models.JSONField(default=dict)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='domain.mobiledashboard')),
            ],
            options={
                'db_table': 'mobile_widgets',
            },
        ),
    ]
