# Generated by Django 6.0.1 on 2026-02-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('endpoint', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=50)),
                ('response_time', models.FloatField(default=0.0)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'health_checks',
                'indexes': [models.Index(fields=['service_name', 'checked_at'], name='health_chec_service_25ca39_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('cpu_usage', models.FloatField(default=0.0)),
                ('memory_usage', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'system_health',
                'indexes': [models.Index(fields=['service_name', 'created_at'], name='system_heal_service_f91b6d_idx')],
            },
        ),
    ]
