# Generated by Django 6.0.1 on 2026-02-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_healthcheck_systemhealth'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=200)),
                ('total_requests', models.IntegerField(default=0)),
                ('successful_requests', models.IntegerField(default=0)),
                ('failed_requests', models.IntegerField(default=0)),
                ('avg_response_time', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'api_metrics',
                'indexes': [models.Index(fields=['endpoint', 'created_at'], name='api_metrics_endpoin_bf3f04_idx')],
            },
        ),
        migrations.CreateModel(
            name='APIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=200)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField()),
                ('response_time', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'api_usage',
                'indexes': [models.Index(fields=['endpoint', 'timestamp'], name='api_usage_endpoin_757c88_idx')],
            },
        ),
    ]
