# Generated by Django 5.2.10 on 2026-01-26 15:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domain", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
    ]
