# Generated by Django 5.2.10 on 2026-02-02 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_organization_alter_userprofile_bio'),
        ('domain', '0002_userprofile_address_userprofile_phone_and_more'),
    ]

    operations = [
    ]
