# Generated by Django 6.0.2 on 2026-02-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0008_campaignanalytics_performancemetric'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntelligenceInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.IntegerField()),
                ('insight_type', models.CharField(max_length=100)),
                ('insight_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketingIntelligence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.IntegerField()),
                ('intelligence_type', models.CharField(max_length=100)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
