# Generated by Django 6.0.2 on 2026-02-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0010_campaignoptimization_optimizationrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.IntegerField()),
                ('model_type', models.CharField(max_length=100)),
                ('conversion_value', models.FloatField()),
                ('attribution_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TouchPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.IntegerField()),
                ('channel', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('touchpoint_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
