# Generated by Django 6.0.2 on 2026-02-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0011_attributionmodel_touchpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('campaign_id', models.IntegerField()),
                ('journey_data', models.JSONField(default=dict)),
                ('status', models.CharField(default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JourneyStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey_id', models.IntegerField()),
                ('stage_name', models.CharField(max_length=100)),
                ('stage_order', models.IntegerField()),
                ('stage_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
