# Generated by Django 6.0.2 on 2026-02-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('event', 'Event'), ('forum', 'Forum'), ('volunteer', 'Volunteer')], max_length=20)),
                ('entity_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=200)),
                ('user_email', models.EmailField(max_length=254)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['feedback_type', 'entity_id'], name='domain_feed_feedbac_bcbef0_idx'), models.Index(fields=['status'], name='domain_feed_status_b7928c_idx')],
            },
        ),
    ]
