# Generated by Django 6.0.2 on 2026-02-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user_id', models.IntegerField()),
                ('to_user_id', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['from_user_id', 'status'], name='domain_conn_from_us_876eb6_idx'), models.Index(fields=['to_user_id', 'status'], name='domain_conn_to_user_5063b8_idx')],
                'unique_together': {('from_user_id', 'to_user_id')},
            },
        ),
    ]
