# Generated by Django 6.0.2 on 2026-02-08 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0003_connection'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('technology', 'Technology'), ('sports', 'Sports'), ('arts', 'Arts'), ('education', 'Education'), ('business', 'Business'), ('other', 'Other')], max_length=50)),
                ('creator_user_id', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('max_members', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['category'], name='domain_inte_categor_4c86d7_idx'), models.Index(fields=['is_active'], name='domain_inte_is_acti_cbed47_idx')],
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('removed', 'Removed')], default='pending', max_length=20)),
                ('role', models.CharField(choices=[('member', 'Member'), ('moderator', 'Moderator'), ('admin', 'Admin')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='domain.interestgroup')),
            ],
            options={
                'indexes': [models.Index(fields=['user_id', 'status'], name='domain_grou_user_id_8c3f3a_idx'), models.Index(fields=['group', 'status'], name='domain_grou_group_i_d8d3c0_idx')],
                'unique_together': {('group', 'user_id')},
            },
        ),
    ]
