# Generated by Django 6.0.2 on 2026-02-08 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0004_interestgroup_groupmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorshipProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('skills_required', models.TextField()),
                ('duration_weeks', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='domain_ment_status_d43c29_idx')],
            },
        ),
        migrations.CreateModel(
            name='MentorMentee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor_user_id', models.IntegerField()),
                ('mentee_user_id', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='domain.mentorshipprogram')),
            ],
            options={
                'indexes': [models.Index(fields=['mentor_user_id', 'status'], name='domain_ment_mentor__d38602_idx'), models.Index(fields=['mentee_user_id', 'status'], name='domain_ment_mentee__7c31c7_idx')],
                'unique_together': {('program', 'mentor_user_id', 'mentee_user_id')},
            },
        ),
    ]
