# Generated by Django 6.0.2 on 2026-02-08 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0005_mentorshipprogram_mentormentee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('participation', 'Participation'), ('contribution', 'Contribution'), ('leadership', 'Leadership'), ('learning', 'Learning')], max_length=50)),
                ('points', models.IntegerField(default=0)),
                ('badge_icon', models.CharField(blank=True, max_length=100)),
                ('criteria', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['category'], name='domain_achi_categor_4819e4_idx'), models.Index(fields=['is_active'], name='domain_achi_is_acti_e2dfdb_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='domain.achievement')),
            ],
            options={
                'indexes': [models.Index(fields=['user_id', 'status'], name='domain_user_user_id_bc2043_idx')],
                'unique_together': {('achievement', 'user_id')},
            },
        ),
    ]
