# Generated by Django 6.0.2 on 2026-02-08 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0006_achievement_userachievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('content_type', models.CharField(choices=[('article', 'Article'), ('document', 'Document'), ('link', 'Link'), ('media', 'Media')], max_length=20)),
                ('content_url', models.URLField(blank=True)),
                ('creator_user_id', models.IntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_collaborative', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['creator_user_id'], name='domain_shar_creator_e77a0b_idx'), models.Index(fields=['status'], name='domain_shar_status_40b3c5_idx'), models.Index(fields=['content_type'], name='domain_shar_content_e87e98_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContentCollaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor'), ('owner', 'Owner')], default='viewer', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to='domain.sharedcontent')),
            ],
            options={
                'indexes': [models.Index(fields=['user_id'], name='domain_cont_user_id_7b2030_idx'), models.Index(fields=['content', 'role'], name='domain_cont_content_89e2fb_idx')],
                'unique_together': {('content', 'user_id')},
            },
        ),
    ]
