# Generated by Django 6.0.2 on 2026-02-08 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0007_sharedcontent_contentcollaboration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rule_type', models.CharField(choices=[('keyword', 'Keyword Filter'), ('spam', 'Spam Detection'), ('profanity', 'Profanity Filter'), ('harassment', 'Harassment Detection')], max_length=20)),
                ('pattern', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['rule_type'], name='domain_mode_rule_ty_14d031_idx'), models.Index(fields=['is_active'], name='domain_mode_is_acti_e78980_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('warning', 'Warning'), ('remove', 'Remove Content'), ('suspend', 'Suspend User'), ('ban', 'Ban User')], max_length=20)),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.IntegerField()),
                ('moderator_id', models.IntegerField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='domain.moderationrule')),
            ],
            options={
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='domain_mode_target__a47f6b_idx'), models.Index(fields=['status'], name='domain_mode_status_651f9d_idx')],
            },
        ),
    ]
