# Generated by Django 6.0.2 on 2026-02-08 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0008_moderationrule_moderationaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('document', 'Document'), ('template', 'Template'), ('guide', 'Guide'), ('tool', 'Tool')], max_length=20)),
                ('created_by', models.IntegerField()),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SharedResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file_url', models.URLField()),
                ('file_type', models.CharField(max_length=50)),
                ('file_size', models.IntegerField(default=0)),
                ('tags', models.JSONField(default=list)),
                ('download_count', models.IntegerField(default=0)),
                ('uploaded_by', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='domain.resourcelibrary')),
            ],
        ),
    ]
