# Generated by Django 6.0.2 on 2026-02-08 15:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0009_resourcelibrary_sharedresource'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('user_growth', 'User Growth'), ('engagement', 'Engagement'), ('content', 'Content'), ('activity', 'Activity')], max_length=20)),
                ('metric_value', models.FloatField()),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EngagementMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('posts_created', models.IntegerField(default=0)),
                ('comments_made', models.IntegerField(default=0)),
                ('likes_given', models.IntegerField(default=0)),
                ('shares_made', models.IntegerField(default=0)),
                ('engagement_score', models.FloatField(default=0.0)),
                ('last_active', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
