# Generated by Django 6.0.2 on 2026-02-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0010_communityanalytics_engagementmetrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rule_type', models.CharField(choices=[('post_created', 'Post Created'), ('comment_made', 'Comment Made'), ('like_received', 'Like Received'), ('share_made', 'Share Made'), ('daily_login', 'Daily Login')], max_length=20)),
                ('points', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('reward_type', models.CharField(choices=[('badge', 'Badge'), ('points', 'Points'), ('achievement', 'Achievement')], max_length=20)),
                ('reward_name', models.CharField(max_length=200)),
                ('points_earned', models.IntegerField(default=0)),
                ('total_points', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
