# Generated by Django 6.0.1 on 2026-01-30 09:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('wallet_type', models.CharField(choices=[('apple_pay', 'Apple Pay'), ('google_pay', 'Google Pay')], max_length=20)),
                ('wallet_token', models.CharField(max_length=255, unique=True)),
                ('device_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mobile_wallets',
                'indexes': [models.Index(fields=['user_id', 'status'], name='mobile_wall_user_id_7beb04_idx')],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wallet_id', models.UUIDField(db_index=True)),
                ('order_id', models.UUIDField(db_index=True)),
                ('transaction_type', models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=255)),
                ('gateway_response', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wallet_transactions',
                'indexes': [models.Index(fields=['wallet_id'], name='wallet_tran_wallet__6c035f_idx'), models.Index(fields=['order_id'], name='wallet_tran_order_i_f9d811_idx')],
            },
        ),
    ]
