# Generated by Django 6.0.1 on 2026-01-26 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=255)),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('role', models.CharField(choices=[('ORGANIZATION', 'Organization'), ('ORGANIZER', 'Organizer'), ('VOLUNTEER', 'Volunteer'), ('ATTENDEE', 'Attendee')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'event_roles',
                'indexes': [models.Index(fields=['event_id', 'user_id'], name='event_roles_event_i_e7d6e5_idx'), models.Index(fields=['user_id', 'is_active'], name='event_roles_user_id_0c2d4d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ORGANIZATION', 'Organization'), ('ORGANIZER', 'Organizer'), ('VOLUNTEER', 'Volunteer'), ('ATTENDEE', 'Attendee')], max_length=50)),
                ('resource', models.CharField(choices=[('EVENT', 'Event'), ('TICKET', 'Ticket'), ('ATTENDEE', 'Attendee'), ('SCHEDULE', 'Schedule')], max_length=50)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('READ', 'Read'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=50)),
            ],
            options={
                'db_table': 'permissions',
                'indexes': [models.Index(fields=['role', 'resource'], name='permissions_role_d8e1e3_idx')],
                'unique_together': {('role', 'resource', 'action')},
            },
        ),
    ]
