# Generated by Django 6.0.1 on 2026-01-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.CharField(db_index=True, max_length=255)),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('MEMBER', 'Member')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'organization_roles',
                'indexes': [models.Index(fields=['organization_id', 'user_id'], name='organizatio_organiz_e4cd14_idx'), models.Index(fields=['user_id', 'is_active'], name='organizatio_user_id_75497d_idx'), models.Index(fields=['organization_id', 'role', 'is_active'], name='organizatio_organiz_9b29ac_idx')],
            },
        ),
    ]
