# Generated by Django 6.0.1 on 2026-01-26 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_organizationrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'custom_roles',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(choices=[('EVENT', 'Event'), ('TICKET', 'Ticket'), ('ATTENDEE', 'Attendee'), ('SCHEDULE', 'Schedule')], max_length=50)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('READ', 'Read'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=50)),
            ],
            options={
                'db_table': 'role_permissions',
            },
        ),
        migrations.CreateModel(
            name='UserCustomRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.CharField(db_index=True, max_length=255)),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_custom_roles',
            },
        ),
        migrations.RemoveIndex(
            model_name='organizationrole',
            name='organizatio_organiz_e4cd14_idx',
        ),
        migrations.RemoveIndex(
            model_name='organizationrole',
            name='organizatio_organiz_9b29ac_idx',
        ),
        migrations.AlterField(
            model_name='organizationrole',
            name='organization_id',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='organizationrole',
            name='role',
            field=models.CharField(default='OWNER', max_length=50),
        ),
        migrations.AddIndex(
            model_name='customrole',
            index=models.Index(fields=['organization_id'], name='custom_role_organiz_ddf51f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customrole',
            unique_together={('organization_id', 'name')},
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='custom_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='domain.customrole'),
        ),
        migrations.AddField(
            model_name='usercustomrole',
            name='custom_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.customrole'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['custom_role', 'resource'], name='role_permis_custom__cc310d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('custom_role', 'resource', 'action')},
        ),
        migrations.AddIndex(
            model_name='usercustomrole',
            index=models.Index(fields=['organization_id', 'user_id'], name='user_custom_organiz_d4ba3d_idx'),
        ),
        migrations.AddIndex(
            model_name='usercustomrole',
            index=models.Index(fields=['user_id', 'is_active'], name='user_custom_user_id_5cb222_idx'),
        ),
    ]
